### ISSUE TITLE
flownative/base provides unsupported python version

### ISSUE THREAD

**Issue by Kaligule** [flownative/docker-base#2]
### Problem

This docker image has python 2.7 installed, which has been out of support for nearly 2 years now.
Please update the provided python version to [a version that is currently in support](https://devguide.python.org/#status-of-python-branches).

### proof

Python version in flownative/base:

`docker run -it flownative/base:2.3.2 python --version` returns `Python 2.7.16`

The base image doesn't have python installed at all:

`docker run -it bitnami/minideb:buster python --version`

    docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "python": executable file not found in $PATH: unknown.

Support ended on 2020-01-01:

https://www.python.org/downloads/

### Why is this bad

To cite from https://www.python.org/doc/sunset-python-2/:

> If people find catastrophic security problems in Python 2, or in software written in Python 2,
> then most volunteers will not help fix them.
> If you need help with Python 2 software,
> then many volunteers will not help you,
> and over time fewer and fewer volunteers will be able to help you.
> You will lose chances to use good tools because they will only run on Python 3,
> and you will slow down people who depend on you and work with you.

**Comment by kdambekalns** [comment]
The `flownative/base` container is based on `bitnami/minideb:buster` as of now. We don't install Python explicitly, but it is a depedency of the packages we do install: dpkg, apt-utils, ca-certificates, supervisor, syslog-ng, logrotate

Building it based on `bitnami/minideb:bullseye` leads to `python` not being available, but the dependency now is to Python 3, `python3` being `Python 3.9.2`

**Comment by robertlemke** [comment]
Thanks for bringing up this topic.

In the meantime we have migrated to Debian Bullseye which comes with Python 3.9 which is supported until October 2025.

For the record: We need Python because we install [Supervisord](http://supervisord.org/introduction.html#platform-requirements).
